### ISSUE TITLE
不知道是不是个bug

### ISSUE THREAD

**Issue by playgamelxh** [QcloudApi/qcloudapi-sdk-php#1]
Warning: substr() expects parameter 1 to be string, array given in src/QcloudApi/Common/Sign.php on line 77
$arr = array(
            'appId'     => $num,
            'op_type'   => 'add',
            'contents'  => $data
        );
$a = $cvm->DataManipulation($arr)  当使用post方法添加数据的时候，不知道对不对

**Comment by QcloudApi** [comment]
无法复现，是不是已经在某次提交中悄悄修复了呢？
如果您确认问题依然存在，请再次打开该问题。
谢谢您的反馈。
