### ISSUE TITLE
怎么通过虚机的id 获取这个虚机所挂载的云硬盘的id？

### ISSUE THREAD

**Issue by hwanginsitein** [QcloudApi/qcloudapi-sdk-php#2]

**Comment by QcloudApi** [comment]
参照demo的示例，里面就是调用cvm模块的DescribeInstances接口获取虚拟机列表，你可以增加参数instanceIds.0指定虚拟机id，然后在返回值里获取到挂载的云硬盘的id，例如echo $a['instanceSet'][0]['diskInfo']['storageId']，如果需要的是其他字段信息，或者是多个虚拟机的云硬盘id，或者是一个虚拟机多个硬盘的信息，请酌情处理。

SDK是不负责这种跟业务具体操作相关的答疑的，请您结合官方api文档，使用SDK构建您强大的代码吧。
