### ISSUE TITLE
还能用么

### ISSUE THREAD

**Issue by webclz** [QcloudApi/qcloudapi-sdk-php#3]
这个sdk还能用吗？都报以下错误
Error code:6100. message:本版本内不支持的接口或者接口已经被废弃，请参考该接口的文档

**Comment by shtse8** [comment]
這麼久還沒有人回覆過。。。

**Comment by wkl7123** [comment]
可以用的，我猜测是@skytree8 写错了`QcloudApi::load(QcloudApi::MODULE_NAME, $config);`里面的第一个参数，比如本该在`QcloudApi::MODULE_IMAGE`下的接口`DescribeImages`，这里却写填写了`QcloudApi::MODULE_CVM`，就会报`不支持的接口`这个错误

**Comment by QcloudApi** [comment]
@webclz 能用的 @wkl7123 的回答是正确的，6100错误表明接口不存在
