### ISSUE TITLE
composer无效，能解决下吗？

### ISSUE THREAD

**Issue by ChenSee** [QcloudApi/qcloudapi-sdk-php#6]
![image](https://user-images.githubusercontent.com/11918919/27112778-ad564442-50eb-11e7-9e52-fd673fa29f2b.png)

**Comment by shikuntian** [comment]
腾讯的大神，文档能维护好点么

**Comment by ghost** [comment]
https://github.com/wonderful60/qcloudapi-sdk-php 我这个Fork版本支持了namespace

**Comment by QcloudApi** [comment]
我们已经把项目打包放到了packagist.org上，目前使用composer安装依赖没有问题。
