### ISSUE TITLE
刚申请的api秘钥就不能用了，配额用完

### ISSUE THREAD

**Issue by slince** [QcloudApi/qcloudapi-sdk-php#8]
```
QcloudApi_Common_Error {#441 ▼
  #_code: 4000
  #_message: "(503) Quota run out"
  #_ext: ""
}
```

在这个链接上生成的秘钥 https://console.qcloud.com/capi； 问下一个秘钥配额是什么样的有没有文档可以说明的；还有我这个秘钥是刚生成的为啥就说配额用完了

**Comment by QcloudApi** [comment]
密钥配额并非sdk相关的，而是和使用某个具体服务相关的，我们无法解决这个问题。

您的问题中有用的信息实在太少，我们甚至无法把这个问题转交给其他同事处理。充足的信息能保证有效沟通，确保您的问题尽快解决。
至少请告知我们您使用的是哪个服务的API，哪个版本（有些服务有多个版本，有些只有一个版本），调用的是哪个接口，使用的是什么参数，您的secretid是多少（我们不需要您提供secretkey，这是和密码类似的敏感信息，请不要泄漏给任何您不信任的人，尤其不要贴在公网上），调用发生的时间。如果可以的话，还可以在您的代码中打印完整的回包提供给我们。

谢谢。

**Comment by slince** [comment]
你好！
> 您的secretid是多少

id是`AKIDzxmPq6TC06CC2jGvqGajgR7laLxUsRhm`

> 至少请告知我们您使用的是哪个服务的AP

是文智的服务关键词提取服务，链接是 http://wiki.open.qq.com/wiki/%E5%85%B3%E9%94%AE%E8%AF%8D%E6%8F%90%E5%8F%96API

> 还可以在您的代码中打印完整的回包提供给我们。

调用代码：
```php
        $wenZhi = $this->getQCloudFactory()->create(\QcloudApi::MODULE_WENZHI);
        $result = $wenZhi->TextKeywords([
            'title' => $content,
            'content' => $content,
            'channel' => 'CHnews_news_others'
        ]);
```


只打印 error的结果是：
```php
       if ($result === false) {
            dump($wenZhi->getError());exit;
        }
```
![image](https://user-images.githubusercontent.com/3785826/34325430-423aa3b4-e8cc-11e7-80ca-fd538e145435.png)

打印error和response的结果是：
```php
       if ($result === false) {
            dump($wenZhi->getResponse());
            dump($wenZhi->getError());exit;
        }
```
![image](https://user-images.githubusercontent.com/3785826/34325432-5a4ae6c6-e8cc-11e7-9366-e2c80218b1c1.png)

我也很费解多打印一个参数错误的原因竟然是不一样的.

**Comment by QcloudApi** [comment]
getResponse函数并未定义，因而默认调用了__call方法，将其作为API的接口对待，wenzhi模块没有getResponse接口，因而报错6100

已将Quota run out问题转交wenzhi模块咨询

**Comment by slince** [comment]
@QcloudApi  你好有答案了吗

**Comment by QcloudApi** [comment]
登录控制台 https://console.cloud.tencent.com/nlp/manage_app.cgi
领取免费额度，或者付费购买
![image](https://user-images.githubusercontent.com/9277281/34345569-f86391d2-ea2a-11e7-942a-3098cca72249.png)

文智文档：
http://nlp.qq.com/help.cgi?topic=api#
https://cloud.tencent.com/document/product/271/2813

如有其他问题直接在控制台发起工单，咨询文智相关问题，sdk不再做咨询解答，谢谢

**Comment by slince** [comment]
好的 谢谢
